network = "testnet"

[blocklist_client]
host = "127.0.0.1"
port = 8080

[block_notifier]
server = "tcp://localhost:60401"
retry_interval = 10
max_retry_attempts = 5
ping_interval = 60
subscribe_interval = 10

[stacks.api]
endpoint = "http://localhost:3999"

[stacks.node]
endpoint = "http://localhost:20443"
# This is the start height of the first EPOCH 3.0 block on the stacks
# blockchain.
nakamoto_start_height = 31

[contracts]
deposit_contract_address = ""
deposit_contract_name = "sbtc-deposit"
