version: '3.2'

services:
  bitcoin:
    image: bitcoin:latest
    container_name: bitcoin
    stop_grace_period: 5s
    build:
      context: ./bitcoin/docker
      args:
        VERSION: '25.0'
    ports:
      - 18444:18444
      - 18443:18443
      - 18433:18433
    environment:
      - ENV='DEV'
      - BTC_NETWORK='regtest'
      - BTC_DISABLEWALLET='0'
      - BTC_TXINDEX='1'
      - BTC_RPCBIND='0.0.0.0'
      - BTC_RPCALLOWIP='0.0.0.0/0'
      - BTC_RPCPASSWORD='devnet'
      - BTC_RPCUSER='devnet'
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    stop_grace_period: 5s
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  mariadb:
    image: mariadb:10.5.21
    container_name: mariadb
    stop_grace_period: 5s
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE='mempool'
      - MYSQL_USER='mempool'
      - MYSQL_PASSWORD='mempool'
      - MYSQL_ROOT_PASSWORD='admin'
  bitcoin-miner:
    image: miner:latest
    container_name: miner
    stop_grace_period: 5s
    build:
      context: ./bitcion-miner-sidecar/docker
    depends_on:
      - bitcoin
    environment:
      INIT_BTC_BLOCKS: 200
      BTC_BLOCK_GEN_TIME: 10
  stacks:
    image: stacks:latest
    container_name: stacks
    stop_grace_period: 5s
    build:
      context: ./stacks/docker
    ports:
      - 20444:20444
      - 20443:20443
    depends_on:
      - bitcoin
      - bitcoin-miner
    environment:
      - STACKS_LOG_DEBUG=0
      - STACKS_LOG_JSON=0
  stacks-api:
    image: stacks-api:latest
    container_name: stacks-api
    stop_grace_period: 5s
    build:
      context: ./stacks-api/docker
      args:
        GIT_URI: 'https://github.com/hirosystems/stacks-blockchain-api.git'
        GIT_BRANCH: 'v7.10.0-nakamoto.7'
    ports:
      - 3999:3999
      - 3700:3700
    depends_on:
      - postgres
      - stacks
      - bitcoin
    environment:
      - NODE_ENV=production
      - GIT_TAG=master
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DATABASE=postgres
      - STACKS_CHAIN_ID=0x80000000
      - STACKS_CORE_EVENT_PORT=3700
      - STACKS_CORE_EVENT_HOST=0.0.0.0
      - STACKS_BLOCKCHAIN_API_PORT=3999
      - STACKS_BLOCKCHAIN_API_HOST=0.0.0.0
      - STACKS_CORE_RPC_HOST=stacks
      - STACKS_CORE_RPC_PORT=20443
      - API_DOCS_URL=http://localhost:3999/doc
  stacks-explorer:
    image: stacks-explorer
    container_name: stacks-explorer
    stop_grace_period: 5s
    build:
      context: ./stacks-explorer/docker
      args:
        GIT_URI: https://github.com/hirosystems/explorer.git
        GIT_BRANCH: v1.170.1
    ports:
      - 3020:3000
    depends_on:
      - bitcoin
      - stacks
      - stacks-api
      - postgres
    environment:
      - NEXT_PUBLIC_MAINNET_API_SERVER=http://127.0.0.1:3999
  electrs:
    image: electrs:latest
    container_name: electrs
    stop_grace_period: 5s
    build:
      context: ./electrs/docker
    ports:
      - 60401:60401
      - 3002:3002
    depends_on:
      - bitcoin
      - bitcoin-miner
    environment:
      - RUST_BACKTRACE='1'
      - BITCOIN_RPC_HOST='bitcoin-regtest-service.bitcoin'
      - BITCOIN_RPC_PORT='18443'
  sbtc:
    image: sbtc:latest
    container_name: sbtc
    stop_grace_period: 5s
    restart: on-failure
    build:
      context: ./../
      dockerfile: ./devenv/sbtc/docker/Dockerfile
    depends_on:
      - bitcoin
      - stacks
      - stacks-explorer
      - stacks-api
      - mempool-web
      - bitcoin-miner
    environment:
      RUST_BACKTRACE: 1
    volumes:
      - $PWD/sbtc/docker/config.json:/romeo/config.json
  mempool-web:
    image: mempool/frontend:latest
    container_name: mempool-web
    stop_grace_period: 5s
    depends_on:
      - mempool-api
      - mariadb
    user: "1000:1000"
    restart: on-failure
    ports:
      - 8083:8083
    environment:
      - FRONTEND_HTTP_PORT="8083"
      - BACKEND_MAINNET_HTTP_HOST="mempool-backend-service.mempool"
    command: "./wait-for mariadb:3306 --timeout=720 -- nginx -g 'daemon off;'"
  mempool-api:
    image: mempool/backend:latest
    container_name: mempool-api
    stop_grace_period: 5s
    depends_on:
      - electrs
      - mariadb
    user: "1000:1000"
    restart: on-failure
    ports:
      - 8999:8999
    environment:
      - MEMPOOL_BACKEND='electrum'
      - ELECTRUM_HOST='electrs-service.electrs'
      - ELECTRUM_PORT='60401'
      - ELECTRUM_TLS_ENABLED='false'
      - CORE_RPC_HOST='bitcoin-regtest-service.bitcoin'
      - CORE_RPC_PORT='18443'
      - CORE_RPC_USERNAME='devnet'
      - CORE_RPC_PASSWORD='devnet'
      - DATABASE_ENABLED='true'
      - DATABASE_HOST='mariadb-service.mariadb'
      - DATABASE_DATABASE='mempool'
      - DATABASE_USERNAME='mempool'
      - DATABASE_PASSWORD='mempool'
      - STATISTICS_ENABLED='true'
    command: "./wait-for-it.sh mariadb:3306 --timeout=720 --strict -- ./start.sh"
