# Services.
# ------------------------------------------------------------------------------
services:
  postgres:
    image: postgres:16.3
    stop_grace_period: 5s
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: signer

  sbtc-signer:
    image: blockstack/sbtc:signer-latest
    entrypoint: "/bin/bash -c '/usr/local/bin/signer -c /signer-config.toml --migrate-db'"
    environment:
      RUST_LOG: warn,signer=debug
      SIGNER_SIGNER__P2P__LISTEN_ON: tcp://0.0.0.0:4122
      SIGNER_SIGNER__DB_ENDPOINT: postgresql://postgres:postgres@postgres:5432/signer
      SIGNER_SIGNER__PRIVATE_KEY: 3ec0ca5770a356d6cd1a9bfcbf6cd151eb1bd85c388cc00648ec4ef5853fdb7401
    volumes:
      - ./sbtc/signer/signer-config.toml:/signer-config.toml
    ports:
      - "8801:8801"

  blocklist-client:
    image: blockstack/sbtc:blocklist-client-latest
    entrypoint: "/bin/bash -c '/usr/local/bin/blocklist-client -c /blocklist-client-config.toml'"
    volumes:
      - ./config/blocklist-client-config.toml:/blocklist-client-config.toml
    ports:
      - "3032:3032"
