---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitcoin-regtest-deployment
  namespace: bitcoin
  labels:
    app: bitcoin-regtest
  
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: bitcoin-regtest
  
  template:
    metadata:
      labels:
        app: bitcoin-regtest
    
    spec:
      containers:
      - name: bitcoin-regtest-container
        image: local/bitcoin:v3
        imagePullPolicy: Never
        
        resources:
          requests:
            memory: 128Mi
            cpu: 50m
          limits:
            memory: 256Mi
            cpu: 100m
        
        ports:
        - containerPort: 18444
          protocol: TCP
        - containerPort: 18443
          protocol: TCP
        - containerPort: 18433
          protocol: TCP
        - containerPort: 18444
          protocol: UDP
        - containerPort: 18443
          protocol: UDP
        - containerPort: 18433
          protocol: UDP

        env:
          - name: ENV
            value: "DEV"
          - name: 'BTC_NETWORK'
            value: "regtest"
          - name: 'BTC_DISABLEWALLET'
            value: "0"
          - name: 'BTC_TXINDEX' 
            value: "1"
          - name: 'BTC_RPCBIND'
            value: "0.0.0.0"
          - name: 'BTC_RPCALLOWIP'
            value: "0.0.0.0/0"
          - name: 'BTC_RPCPASSWORD'
            value: "devnet"
          - name: 'BTC_RPCUSER'
            value: 'devnet'

      - name: bitcoin-miner-sidecar
        image: local/bitcoin-miner-sidecar:v3
        imagePullPolicy: Never
        
        resources:
          requests:
            memory: 128Mi
            cpu: 50m
          limits:
            memory: 256Mi
            cpu: 100m

        env:
          - name: INIT_BTC_BLOCKS
            value: "200"
          - name: BTC_BLOCK_GEN_TIME
            value: "10"
          - name: BITCOIN_RPC_HOST
            value: "localhost"
          - name: BITCOIN_RPC_PORT
            value: "18443"
          - name: MINER_ADDRESS
            value: "n3GRiDLKWuKLCw1DZmV75W1mE35qmW2tQm"