apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  namespace: mariadb
  labels:
    app: mariadb
  
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: mariadb
  
  template:
    metadata:
      labels:
        app: mariadb
    
    spec:
      containers:
      - name: mariadb-container
        image: mariadb:10.5.21
        imagePullPolicy: IfNotPresent
        
        livenessProbe:
          exec:
            command:
            - bash
            - -c
            - mysqladmin -u ${MYSQL_USER} -p ${MYSQL_PASSWORD} ping
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          
        readinessProbe:
          exec:
            command:
            - bash
            - -c
            - mysql -u ${MYSQL_USER} -p ${MYSQL_PASSWORD} -e "SELECT 1"
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
        
        resources:
          requests:
            memory: 128Mi
            cpu: 50m
          limits:
            memory: 256Mi
            cpu: 100m
        
        ports:
        - containerPort: 3306
          protocol: TCP
        env:
          - name: MYSQL_DATABASE
            value: "mempool"
          - name: MYSQL_USER
            value: "mempool"
          - name: MYSQL_PASSWORD
            value: "mempool"
          - name: MYSQL_ROOT_PASSWORD
            value: "admin"