---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mempool-frontend-deployment
  namespace: mempool-frontend
  labels:
    app: mempool-frontend
  
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: mempool-frontend
  
  template:
    metadata:
      labels:
        app: mempool-frontend
    
    spec:
      containers:
      - name: mempool-frontend-container
        image: mempool/frontend:latest
        imagePullPolicy: IfNotPresent
        
        # livenessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /
        #     port: 8083
        #     scheme: HTTP
        #   periodSeconds: 10
        #   successThreshold: 1
        #   timeoutSeconds: 10
        #   initialDelaySeconds: 30
        
        # readinessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /
        #     port: 8083
        #     scheme: HTTP
        #   periodSeconds: 10
        #   successThreshold: 1
        #   timeoutSeconds: 10
        #   initialDelaySeconds: 30
        
        resources:
          requests:
            memory: 128Mi
            cpu: 50m
          limits:
            memory: 256Mi
            cpu: 100m
        
        ports:
        - containerPort: 8083
          protocol: TCP

        env:
          - name: FRONTEND_HTTP_PORT
            value: "8083"
          - name: BACKEND_MAINNET_HTTP_HOST
            value: "mempool-backend-service.mempool"