---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mempool-backend-deployment
  namespace: mempool-backend
  labels:
    app: mempool-backend
  
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: mempool-backend
  
  template:
    metadata:
      labels:
        app: mempool-backend
    
    spec:
      containers:
      - name: mempool-backend-container
        image: mempool/backend:latest
        imagePullPolicy: IfNotPresent
        
        # livenessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /
        #     port: 8999
        #     scheme: HTTP
        #   periodSeconds: 10
        #   successThreshold: 1
        #   timeoutSeconds: 10
        #   initialDelaySeconds: 30
        
        # readinessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /
        #     port: 8999
        #     scheme: HTTP
        #   periodSeconds: 10
        #   successThreshold: 1
        #   timeoutSeconds: 10
        #   initialDelaySeconds: 30
        
        resources:
          requests:
            memory: 128Mi
            cpu: 50m
          limits:
            memory: 256Mi
            cpu: 100m
        
        ports:
        - containerPort: 8999
          protocol: TCP

        env:
          # Connect to electrs host
          - name: MEMPOOL_BACKEND
            value: "electrum"
          - name: ELECTRUM_HOST
            value: "electrs-service.electrs"
          - name: ELECTRUM_PORT
            value: "60401"
          - name: ELECTRUM_TLS_ENABLED
            value: "false"
          # Connect to bitcoin rpc
          - name: CORE_RPC_HOST
            value: "bitcoin-regtest-service.bitcoin"
          - name: CORE_RPC_PORT
            value: "18443"
          - name: CORE_RPC_USERNAME
            value: "devnet"
          - name: CORE_RPC_PASSWORD
            value: "devnet"
          - name: DATABASE_ENABLED
            value: "true"
          - name: DATABASE_HOST
            value: "mariadb-service.mariadb"
          - name: DATABASE_DATABASE
            value: "mempool"
          - name: DATABASE_USERNAME
            value: "mempool"
          - name: DATABASE_PASSWORD
            value: "mempool"
          - name: STATISTICS_ENABLED
            value: "true"