apiVersion: apps/v1
kind: Deployment
metadata:
  name: nakamoto-signer-deployment
  namespace: stacks
  labels:
    app: nakamoto-signer
  
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: nakamoto-signer
  
  template:
    metadata:
      labels:
        app: nakamoto-signer
    
    spec:
      containers:
      - name: nakamoto-signer-container
        image: local/nakamoto-signer:v4
        imagePullPolicy: Never
        
        resources:
          requests:
            memory: 128Mi
            cpu: 50m
          limits:
            memory: 256Mi
            cpu: 100m
        
        ports:
        - containerPort: 30000
          protocol: TCP
        - containerPort: 30000
          protocol: UDP

        env:
          - name: SIGNER_ENDPOINT
            value: "127.0.0.1:30000"
          - name: MY_HTTP_AUTH_TOKEN
            value: "helloworld"
          - name: STACKS_PRIVATE_KEY
            value: "7287ba251d44a4d3fd9276c88ce34c5c52a038955511cccaf77e61068649c17801"
          - name: STACKS_NODE_RPC_HOST
            value: "stacks-node-service.stacks"
          - name: STACKS_NODE_RPC_PORT
            value: "20443"
          - name: RUST_BACKTRACE
            value: '1'