apiVersion: apps/v1
kind: Deployment
metadata:
  name: stacks-node-deployment
  namespace: stacks
  labels:
    app: stacks-node
  
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: stacks-node
  
  template:
    metadata:
      labels:
        app: stacks-node
    
    spec:
      containers:
      - name: stacks-node-container
        image: local/stacks:v6
        imagePullPolicy: Never
        
        resources:
          requests:
            memory: 128Mi
            cpu: 50m
          limits:
            memory: 256Mi
            cpu: 100m
        
        ports:
        - containerPort: 20444
          protocol: TCP
        - containerPort: 20443
          protocol: TCP
        - containerPort: 20444
          protocol: UDP
        - containerPort: 20443
          protocol: UDP

        env:
          - name: STACKS_LOG_DEBUG
            value: "0"
          - name: STACKS_LOG_JSON
            value: "0"
          - name: LOCAL_PEER_SEED
            value: "3fd68a8fcab004754d6fee4756dd9c84ad64ee19a11aa9930893540e1357696f2f73957cd6e92797d7a66d1d3ae4a4ea752a8924fe028f1fc2c06b9d6d0ee0ad"
          - name: STACKS_WORKING_DIR
            value: "/var/stacks"
          - name: MY_HTTP_AUTH_TOKEN
            value: "helloworld"
          - name: SIGNER_ENDPOINT
            value: "nakamoto-signer-service.stacks:30000"
          - name: MINER_KEY
            value: "19ec1c3e31d139c989a23a27eac60d1abfad5277d3ae9604242514c738258efa01"
          - name: BTC_NODE_RPC_HOST
            value: "bitcoin-regtest-service.bitcoin"
          - name: BTC_NODE_RPC_USER
            value: "devnet"
          - name: BTC_NODE_RPC_PASSWORD
            value: "devnet"
          # - name: BTC_RPC_PORT
          #   value: "18443"
          # - name: BTC_P2P_PORT
          #   value: "18444"