[package]
name = "blocklist-client"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "blocklist-client"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror.workspace = true
tracing.workspace = true
tracing-attributes.workspace = true
serde.workspace = true
serde_json.workspace = true
warp = "0.3"
tokio = { version = "1.32.0", features = ["rt-multi-thread", "rt", "macros"] }
reqwest = { version = "0.11", features = ["json"] }
config = "0.11"
once_cell = "1.8.0"
sbtc-signer = { path = "../signer" }

[dependencies.tracing-subscriber]
version = "0.3"
default-features = false
features = ["env-filter", "fmt", "json", "time"]

[dev-dependencies]
mockito = "0.28"