name: Buf CI
on: [push]

jobs:
  buf:
    name: Run Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          version: 1.42.0
          setup_only: true

      - name: Check for Lints
        run: |
          cd protobufs
          buf lint

      - name: Check the Format
        run: | 
          cd protobufs
          buf format --diff --exit-code
