name: Rust Jobs
on: [push]

concurrency:
  # limit concurrency of entire workflow runs for a specific branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: rui314/setup-mold@v1
        with:
          make-default: true
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 22.1.0
          cache: "pnpm"
      - uses: arduino/setup-protoc@v3
        with:
          version: "25.3"
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
          cache-key: "rust-tests"
      - name: Install Package Dependencies
        run: make install
      - name: Run Lints
        run: make lint

  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - uses: rui314/setup-mold@v1
        with:
          make-default: true
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-key: "rust-tests"
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 22.1.0
          cache: "pnpm"
      - uses: arduino/setup-protoc@v3
        with:
          version: "25.3"
      - uses: taiki-e/install-action@v2
        with:
          tool: nextest@0.9.82
      - name: Install Package Dependencies
        run: make install
      - name: Run Unit Tests
        run: make test

  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-20.04
    steps:
      - uses: rui314/setup-mold@v1
        with:
          make-default: true
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-key: "rust-tests"
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 22.1.0
          cache: "pnpm"
      - uses: arduino/setup-protoc@v3
        with:
          version: "25.3"
      - uses: taiki-e/install-action@v2
        with:
          tool: nextest@0.9.82
      - name: Install Package Dependencies
        run: make install
      - name: Start Integration Test Environment
        run: make integration-env-up-ci
      - name: Run Integration Tests
        run: make integration-test
      - name: Stop Integration Test Environment
        run: make integration-env-down-ci
        if: always()

    